---
name: 'Release'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.15.2
          otp-version: 26.0.2

      - name: Create Release Package
        run: mix hex.build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            filter_formatter-${{ github.ref_name }}.tar

      - name: Publish to Hex.pm
        run: mix deps.get && mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
